kind: pipeline
type: docker
name: build-on-push

trigger:
  event:
    - push

steps:
  - name: build
    image: klakegg/hugo:0.118.2-ext-alpine
    environment:
      BASE_URL:
        from_secret: s3_prod_url
    commands:
      - hugo --baseURL $BASE_URL

---
kind: pipeline
type: docker
name: release-on-tag

trigger:
  event:
    - tag

steps:
  - name: build
    image: klakegg/hugo:0.118.2-ext-alpine
    environment:
      BASE_URL:
        from_secret: s3_releases_url
    commands:
      - hugo --baseURL $BASE_URL

  - name: deploy-to-releases
    image: plugins/s3
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      session_token:
        from_secret: aws_session_token
      region:
        from_secret: aws_region

      bucket:
        from_secret: s3_releases_bucket
      target: /${DRONE_TAG}
      source: public/
      delete: true

---
kind: pipeline
type: docker
name: promote-to-production

trigger:
  event:
    - promote
  target:
    - production

steps:
  - name: deploy-to-production
    image: plugins/s3
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      session_token:
        from_secret: aws_session_token
      region:
        from_secret: aws_region

      bucket:
        from_secret: s3_prod_bucket
      source: /${DRONE_TAG}
      source_bucket:
        from_secret: s3_releases_bucket
      delete: true