kind: pipeline
type: docker
name: build-on-push

trigger:
  event:
    - push

steps:
  - name: build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      BASE_URL:
        from_secret: s3_prod_url
    commands:
      - hugo --baseURL $BASE_URL

---
kind: pipeline
type: docker
name: release-on-tag

trigger:
  event:
    - tag

steps:
  - name: build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      BASE_URL:
        from_secret: s3_releases_url
    commands:
      - hugo --baseURL $BASE_URL

  - name: deploy-to-releases
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION:
        from_secret: aws_region
      S3_RELEASES_BUCKET:
        from_secret: s3_releases_bucket
    commands:
      - aws s3 sync public/ s3://$S3_RELEASES_BUCKET/$DRONE_TAG/ --delete

---
kind: pipeline
type: docker
name: promote-to-production

trigger:
  event:
    - promote
  target:
    - production

steps:
  - name: deploy-to-production
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION:
        from_secret: aws_region
      S3_PROD_BUCKET:
        from_secret: s3_prod_bucket
      S3_RELEASES_BUCKET:
        from_secret: s3_releases_bucket
    commands:
      - aws s3 sync s3://${S3_RELEASES_BUCKET}/${DRONE_TAG}/ s3://${S3_PROD_BUCKET}/ --delete